version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      #- image: cimg/openjdk:11.0
      - image: jacobalberty/firebird:v4
    steps:
      - checkout
      - run:
          name: Testing
          command: |
            apt-get update && apt-get install unzip openjdk-11-jdk maven git -y > /dev/null
            git clone https://github.com/matteosusca/dbMigrDemo
            cd dbMigrDemo
            unzip fb.zip > /dev/null
            export FIREBIRD=`pwd`"/fb"
            mvn -f pom.xml test > /dev/null
            mvn clean install > /dev/null
            mvn exec:java -Dexec.mainClass="com.example.CreateDatabase"
            mvn liquibase:update
            mvn exec:java -Dexec.mainClass="com.example.FirebirdDatabaseExplorer"
            mvn flyway:clean
            mvn flyway:migrate
            mvn exec:java -Dexec.mainClass="com.example.FirebirdDatabaseExplorer"
            mvn flyway:validate
            mvn flyway:info
            mvn flyway:repair
            mvn flyway:clean
            mvn flyway:migrate -Dflyway.target=1.2
            mvn exec:java -Dexec.mainClass="com.example.FirebirdDatabaseExplorer"
      - run:
          name: Packaging
          command: |
            mvn -Dmaven.test.skip=true -f pom.xml clean package
            mkdir artifacts
            ls -la target || ls -la
            cp target/*.jar artifacts/          
      - run:
          name: Outdated
          command: mvn -f pom.xml versions:display-dependency-updates
workflows:
  build-test-and-deploy:
    jobs:
      - build
