version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      #- image: cimg/openjdk:11.0
      - image: jacobalberty/firebird:v4
    steps:
      - checkout
      - run:
          name: Testing
          command: |
            apt-get update && apt-get install unzip openjdk-11-jdk maven -y
            git clone https://github.com/matteosusca/dbMigrDemo
            cd dbMigrDemo
            unzip fb.zip
            export FIREBIRD=`pwd`"/fb"
            mvn -v
            mvn -f pom.xml test
            mvn clean install
            mvn exec:java -Dexec.mainClass="com.example.CreateDatabase"
            mvn liquibase:update
      - run:
          name: Packaging
          command: |
            mvn -Dmaven.test.skip=true -f pom.xml clean package
            mkdir artifacts
            ls -la target || ls -la
            cp target/*.jar artifacts/          
      - run:
          name: Outdated
          command: mvn -f pom.xml versions:display-dependency-updates
workflows:
  build-test-and-deploy:
    jobs:
      - build
